import { createWriteStream } from "node:fs";
import { mkdir, rm } from "node:fs/promises";
import * as path from "node:path";
import { pipeline } from "node:stream/promises";
import { Collection, Db, Document, GridFSBucket, ObjectId } from "mongodb";
import type { RcFileRef, RcUpload, MmAttachment } from "./types.js";

/**
 * Extracts attachments from RocketChat's GridFS storage into the import
 * package's `data/` directory, and provides the relative path expected by
 * Mattermost.
 *
 * Known limitations:
 *  - Only the GridFS backend is handled. Others (FileSystem, S3, GoogleStorage)
 *    are reported and skipped.
 *  - A missing file is skipped with a warning (the message is kept).
 */
export class FileExporter {
  private bucket: GridFSBucket;
  private uploads: Collection<Document>;
  private dataAbsDir: string;
  private exported = 0;
  private skipped = 0;
  private seen = new Set<string>();

  constructor(
    db: Db,
    bucketName: string,
    outDir: string,
    dataDir: string,
  ) {
    this.bucket = new GridFSBucket(db, { bucketName });
    this.uploads = db.collection("rocketchat_uploads");
    this.dataAbsDir = path.join(outDir, dataDir);
  }

  get stats() {
    return { exported: this.exported, skipped: this.skipped };
  }

  /**
   * Extracts a file referenced in a message and returns the matching Mattermost
   * attachment, or null if the extraction fails.
   */
  async export(
    ref: RcFileRef,
    seenNames?: Set<string>,
  ): Promise<MmAttachment | null> {
    if (!ref?._id) return null;

    const ids = candidateIds(ref._id);
    const meta = (await this.uploads.findOne({
      _id: { $in: ids } as never,
    })) as RcUpload | null;

    const rawName = meta?.name ?? ref.name ?? ref._id;
    // Skip thumbnails generated by RocketChat (redundant with the image).
    if (/^thumb-/i.test(rawName)) {
      this.skipped++;
      return null;
    }

    const fileName = sanitizeFileName(rawName);

    // Intra-message dedup: RocketChat sometimes lists the same image twice
    // (original + displayed version) under the same name. The name is marked
    // only after a successful extraction (see below) so that a failed copy does
    // not prevent its twin from being extracted.
    if (seenNames?.has(fileName)) return null;
    // Mattermost itself prefixes the "data/" directory to attachment paths:
    // the JSONL path is therefore "<id>/<name>" (WITHOUT "data/"), while the
    // physical file is stored under "data/<id>/<name>" in the zip.
    const relPath = path.posix.join(ref._id, fileName);
    const absPath = path.join(this.dataAbsDir, ref._id, fileName);

    // already extracted during this run (same file reused)
    if (this.seen.has(ref._id)) {
      return { path: relPath };
    }

    if (meta?.store && !meta.store.toLowerCase().includes("gridfs")) {
      console.warn(
        `  ⚠️  Fichier ${ref._id} stocké via "${meta.store}" (non GridFS) — ignoré.`,
      );
      this.skipped++;
      return null;
    }

    await mkdir(path.dirname(absPath), { recursive: true });
    // GridFS _ids are strings in RocketChat, but may also be ObjectIds
    // depending on the instance: we try both forms.
    let lastErr: unknown;
    for (const id of ids) {
      try {
        await pipeline(
          this.bucket.openDownloadStream(id as never),
          createWriteStream(absPath),
        );
        this.seen.add(ref._id);
        seenNames?.add(fileName);
        this.exported++;
        return { path: relPath };
      } catch (err) {
        lastErr = err;
      }
    }
    // clean up the empty directory left by the failure
    await rm(path.dirname(absPath), { recursive: true, force: true });
    console.warn(
      `  ⚠️  Échec extraction fichier ${ref._id} (${fileName}): ${
        (lastErr as Error)?.message ?? "introuvable"
      }`,
    );
    this.skipped++;
    return null;
  }

  /** Extracts all files of a message (`file` and `files` fields). */
  async exportAll(
    file: RcFileRef | undefined,
    files: RcFileRef[] | undefined,
  ): Promise<MmAttachment[]> {
    const refs: RcFileRef[] = [];
    if (files?.length) refs.push(...files);
    else if (file) refs.push(file);

    const out: MmAttachment[] = [];
    const seenNames = new Set<string>(); // dedup by name within the message
    for (const ref of refs) {
      const att = await this.export(ref, seenNames);
      if (att) out.push(att);
    }
    return out;
  }
}

/**
 * Reduces a file name to printable ASCII. Zip tools do not always flag names as
 * UTF-8 (and macOS/Linux differ on NFC/NFD), which breaks the match between the
 * JSONL path and the zip entry for accented names. We therefore transliterate
 * accents → ASCII and drop the rest.
 */
function sanitizeFileName(name: string): string {
  const ascii = name
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // strip combining accents
    .replace(/[^ -~]/g, "") // keep only printable ASCII
    .replace(/[/\\]/g, "_")
    .replace(/\s+/g, " ")
    .trim();
  return ascii || "fichier";
}

/**
 * Returns the identifier forms to try when locating a file. RocketChat usually
 * stores strings (including 24-character hex); we try the string first, then
 * the ObjectId as a fallback.
 */
function candidateIds(id: string): (ObjectId | string)[] {
  const out: (ObjectId | string)[] = [id];
  try {
    if (ObjectId.isValid(id) && new ObjectId(id).toString() === id) {
      out.push(new ObjectId(id));
    }
  } catch {
    /* ignore */
  }
  return out;
}
